name: test and maybe deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build image
      run: make image

    - name: Run tests
      run: make run-tests

    - name: Run mypy
      run: make mypy

    - name: Ruff
      run: make ruff

  deploy:
    needs: test
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build dist
        run: make build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
