name: tests

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
#  test:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Build image
#      run: make image
#
#    - name: Run tests
#      run: make run-tests
#
#    - name: Run mypy
#      run: make mypy

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJGQxNWIxNTJkLTI1OWYtNDQ0Mi04OGZmLWI2Y2M4NGFmNDZhYgACKlszLCI3NWVlMThkZi1iYWZkLTRkMGYtODMzNi1mZWVjNjQ0YmI1YjgiXQAABiBCWspjuU64eKdFamKGGoT-1IIN5ecMj9LCEsnw4Q-8Bw
        run: |
          echo $TWINE_PASSWORD
          pip install twine
          make build
          python3 -m twine upload --verbose --non-interactive --repository pypi dist/*
