name: tests

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
#  test:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Build image
#      run: make image
#
#    - name: Run tests
#      run: make run-tests
#
#    - name: Run mypy
#      run: make mypy

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJDQ0YzZlYjAzLTZiNzYtNDM3YS05ZmQyLTMxYTc0Yzg2NzM4YwACIlsxLFsiZnVuY3Rpb25hbC1wYXJzaW5nLWxpYnJhcnkiXV0AAixbMixbIjZiYTEzODQ5LTJiNGUtNDg1My1iNjI0LTU3NzI1ZmNiMTNiNSJdXQAABiC1LhoRfHVMosaX5yK-lVwwRk-zKuKheGBO-pVJN2lwjw
        run: |
          echo $TWINE_PASSWORD
          pip install twine
          make build
          python3 -m twine upload --verbose --non-interactive --repository pypi dist/*
