name: tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build image
      run: make image

    - name: Run tests
      run: make run-tests

    - name: Run mypy
      run: make mypy
